ipc = on
preload = /home/Frillion/Wallpapers/1920x1080/sifoops_1_1920x1080.png
preload = /home/Frillion/Wallpapers/1920x1080/sifoops_2_1920x1080.png
preload = /home/Frillion/Wallpapers/1920x1080/Sifded.webp

wallpaper {
    monitor = eDP-1
    path = /home/Frillion/Wallpapers/1920x1080/sifoops_1_1920x1080.png
    fit_mode = cover
}
